### ISSUE TITLE
vSphere: Resource bridge VM deployment failing to set DNS Server

### ISSUE THREAD

**Issue by tobyjrreu** [Azure/ArcResourceBridge#6]
Hi, I've noticed when using a ARM template to deploy a VM (Microsoft.ConnectedVMwarevSphere virtualMachines) with the DNS parameter set in the parameter file, it's not applied to the VM and in the vmoperator logs I see:
"dnsServers":null,"primaryWinsServer":"","secondaryWinsServer":""
but there's no variable in the template for either winServer(s).
IP, Subnet and Gateway all work correctly though and this is the same in both 1.0.9 and 1.0.10

**Comment by alt-key** [comment]
Hey tobyjrreu! Could you share the ARM template you are using so we can take a look? Thanks for reaching out.

**Comment by tobyjrreu** [comment]
Hi Aline,

Sure thanks for getting back!
I've been referring to this: Microsoft.ConnectedVMwarevSphere/virtualMachines - Bicep, ARM template & Terraform AzAPI reference | Microsoft Learn<https://learn.microsoft.com/en-us/azure/templates/microsoft.connectedvmwarevsphere/virtualmachines?pivots=deployment-language-arm-template>

For background (if it helps):
I initally followed the portal template to Create an Azure Arc virtial machine, then download the parameters and template file (attached for reference), then updated it (as per the ARM MS Doc) to add DNS Servers under the ipsettings object (can be seen in the attached).
The VM deployed just fine via the bridge (1.0.10 template) using Azure CLI from a local machine with the client settings for the IP Address, Subnet and gateway all applying just fine. but nothing for DNS servers, that's when in the logs for vmware operator on the bridge I noticed the references to DNS null and the primary and secondary winservers.

We've also verified and deployed by the terrarform template (by a collegaue) and that too failed on the DNS element.

Let me know if you need any additonal information/.


Best regards,
Toby Reynolds | トビ`
Senior Cloud Transformation Specialist | EMEA IT

[cid:0248c077-690f-4d6a-9909-e320525afe1d] Chat with me on ***@***.***>


Mobile:          +44 (0) 7919 571490

Ricoh Europe PLC, 5th Floor , The Junction, Station Road , Watford , Hertfordshire, WD17 1ET

Annual leave:14th C 15th Nov & 24th-25th Nov,
[cid:50e6e2f2-1bc6-4a7b-8d4e-a9f18c866b4c]

________________________________

**Comment by alt-key** [comment]
Aloha tobyjrreu!

I reached out to the Arc enabled VMware team and they are aware of this issue. Snehith also mentioned that you might've emailed him back in December, so he is keeping track. Their response: 

The DNS Settings properties don't yet work and roll out is in progress to add support for it. 

Feel free to message me or Snehith Muvva on LinkedIn for periodic updates on this.

For now, since this isn't an Arc resource bridge issue, I will close out this issue.

**Comment by alt-key** [comment]
For now, since this isn't an Arc resource bridge issue, I will close out this issue.

**Comment by aronip** [comment]
@tobyjrreu The changes to support specifying DNS settings at the time of VM (Microsoft.ConnectedVMwarevSphere virtualMachines) creation have been rolled out now. Feel free to try out the scenario again. Let us know if you face any issues.
